In [2]:
import numpy as np

In [3]:
#Question1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [4]:
'''Answer1.'''
arr = np.random.randint(1, 100, [3,3])
print(arr)
'''Here we interchange row and column'''
arrT = arr.T
print(arrT)

[[74 59 32]
 [37  9  6]
 [98 13 29]]
[[74 37 98]
 [59  9 13]
 [32  6 29]]


In [5]:
#Question2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [6]:
'''Answer2. Here we use generator to generate the entities for the question'''
iterator =  (i for i in range(10))
iterarray = np.fromiter(iterator, int)
print(iterarray)
'''Now we are reshaping it'''
res = iterarray.reshape(2,5)
print(res)
res2 = iterarray.reshape(5, 2)
print(res2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
#Question3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [8]:
'''Answer3.'''
arr = np.random.randn(4,4)
print(arr)

padded_array = np.pad(arr, pad_width=1, constant_values=0)
print(padded_array)

[[ 0.23661743  0.83752797  1.01819303  0.73165046]
 [ 0.14571784  0.2805809   0.7448981  -0.69984379]
 [-0.02292244  0.35124631  0.67638224 -1.36727955]
 [-1.12929514  0.17629555  1.05884227  0.03958071]]
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.23661743  0.83752797  1.01819303  0.73165046  0.        ]
 [ 0.          0.14571784  0.2805809   0.7448981  -0.69984379  0.        ]
 [ 0.         -0.02292244  0.35124631  0.67638224 -1.36727955  0.        ]
 [ 0.         -1.12929514  0.17629555  1.05884227  0.03958071  0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


In [9]:
#Question4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [10]:
'''Answer4.'''
arr = np.arange(10, 60, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [11]:
#Question5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [12]:
'''Answer5.'''
string = "python, numpy, pandas"
string.split(",")

arr = np.array(string.split(","))
print(arr)

# Uppercase
uppercase_array = np.char.upper(arr)

# Lowercase
lowercase_array = np.char.lower(arr)

# Title case
titlecase_array = np.char.title(arr)

print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title case:", titlecase_array)

['python' ' numpy' ' pandas']
Uppercase: ['PYTHON' ' NUMPY' ' PANDAS']
Lowercase: ['python' ' numpy' ' pandas']
Title case: ['Python' ' Numpy' ' Pandas']


In [13]:
#Question6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [17]:
'''Answer6.'''
wrd_arr = np.array("Mario, Dragonball, Ben-10, Bunny, JhonnyTest")
spaced_words = np.char.join(" ", wrd_arr)
spaced_words

array('M a r i o ,   D r a g o n b a l l ,   B e n - 1 0 ,   B u n n y ,   J h o n n y T e s t',
      dtype='<U87')

In [18]:
#Question7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [23]:
'''Answer7.'''
arr1 = np.random.randint(1,5, [3,3])
arr2 = np.random.randint(1,5, [3,3])

print(arr1)
print(arr2)

print("addition", np.add(arr1, arr2))
print("Subtraction", np.subtract(arr1, arr2))
print("Multiplication", np.multiply(arr1, arr2))
print("Division", np.divide(arr1, arr2))


[[3 2 2]
 [1 4 2]
 [2 2 2]]
[[4 1 4]
 [3 2 3]
 [1 2 2]]
addition [[7 3 6]
 [4 6 5]
 [3 4 4]]
Subtraction [[-1  1 -2]
 [-2  2 -1]
 [ 1  0  0]]
Multiplication [[12  2  8]
 [ 3  8  6]
 [ 2  4  4]]
Division [[0.75       2.         0.5       ]
 [0.33333333 2.         0.66666667]
 [2.         1.         1.        ]]


In [24]:
#Question8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [29]:
'''Answer8.'''
im = np.eye(5,5)
print(im)
diag_im = np.diag(im)
print("Diagonal elements are ", diag_im)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements are  [1. 1. 1. 1. 1.]


In [30]:
#Question9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [40]:
'''Answer9.'''
arr = np.random.randint(0, 1000, 100)
print(arr)

def is_prime(num):
    count = 0
    i = 1
    while(i<=num):
        if(num%i==0):
            count+=1
        i+=1
    if(count == 2):
        return True
    
prime_numbers = [i for i in arr if is_prime(i)]
print("Prime Number", prime_numbers)

[418 550 987  73 227 738 515 673 439 396  90  95 889 138 436 101 644 587
 948 957 394 905 246 197 788 488 700 535 716 791 428 743 369 311 466 572
 137 670 505 747 525 987 592 882 522 650 891 337 450 274 449 617 298  41
 990 933 912 106  84 995 513  26 408 964 656 463 744 673 773 481 985  10
 609 552 799 227 275 112 405 184 793 916 156 594 889 848 514 396 768 287
 722   3 750 595 286 557 853 535 581 592]
Prime Number [np.int32(73), np.int32(227), np.int32(673), np.int32(439), np.int32(101), np.int32(587), np.int32(197), np.int32(743), np.int32(311), np.int32(137), np.int32(337), np.int32(449), np.int32(617), np.int32(41), np.int32(463), np.int32(673), np.int32(773), np.int32(227), np.int32(3), np.int32(557), np.int32(853)]


In [41]:
#Question.10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [52]:
'''Answer.10.'''
'''Assuming 28 days in a month'''
daily_temperatures = np.random.randint(25, 45, 28)
print(daily_temperatures)
'''assuming 4 weeks in a month'''
weekly_averages = np.mean(daily_temperatures.reshape(4, 7), axis=1)
print(weekly_averages)

[44 37 39 42 43 30 31 38 41 26 37 43 25 43 25 28 33 31 31 35 32 38 44 36
 39 34 35 41]
[38.         36.14285714 30.71428571 38.14285714]
