In [1]:
import numpy as np

In [ ]:
#Question1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [12]:
'''Answer1.'''
arr = np.random.randint(1, 100, [3,3])
print(arr)
'''Here we interchange row and column'''
arrT = arr.T
print(arrT)

[[83 80 66]
 [14 14 10]
 [96 22 44]]
[[83 14 96]
 [80 14 22]
 [66 10 44]]


In [ ]:
#Question2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [16]:
'''Answer2. Here we use generator to generate the entities for the question'''
iterator =  (i for i in range(10))
iterarray = np.fromiter(iterator, int)
print(iterarray)
'''Now we are reshaping it'''
res = iterarray.reshape(2,5)
print(res)
res2 = iterarray.reshape(5, 2)
print(res2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
#Question3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [31]:
'''Answer3.'''
arr = np.random.randn(4,4)
print(arr)

padded_array = np.pad(arr, pad_width=1, constant_values=0)
print(padded_array)

[[-2.08221906  0.53875469  0.2851401   0.98884308]
 [ 1.75247593 -0.77332459  1.4348809   0.87905573]
 [-0.50458894 -1.41473345  0.88118412  1.11527307]
 [ 1.52676136  0.65289174  0.55118886  1.31567252]]
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.         -2.08221906  0.53875469  0.2851401   0.98884308  0.        ]
 [ 0.          1.75247593 -0.77332459  1.4348809   0.87905573  0.        ]
 [ 0.         -0.50458894 -1.41473345  0.88118412  1.11527307  0.        ]
 [ 0.          1.52676136  0.65289174  0.55118886  1.31567252  0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


In [32]:
#Question4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [33]:
'''Answer4.'''
arr = np.arange(10, 60, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [34]:
#Question5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [46]:
'''Answer5.'''
string = "python, numpy, pandas"
string.split(",")

arr = np.array(string.split(","))
print(arr)

# Uppercase
uppercase_array = np.char.upper(arr)

# Lowercase
lowercase_array = np.char.lower(arr)

# Title case
titlecase_array = np.char.title(arr)

print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title case:", titlecase_array)

['python' ' numpy' ' pandas']
Uppercase: ['PYTHON' ' NUMPY' ' PANDAS']
Lowercase: ['python' ' numpy' ' pandas']
Title case: ['Python' ' Numpy' ' Pandas']
